#!/bin/bash

commit_message=$(cat "$1")

# Merge commits zijn een uitzondering
if echo "$commit_message" | grep -qE "^Merge branch"; then
  exit 0
fi

issue_number_pattern="^#([0-9]+)|hotfix|boyscout "

# Checked of de commit message start met een issue nummer
if ! echo "$commit_message" | grep -qE "$issue_number_pattern"; then
  echo "Fout: commit messages moeten beginnen met een issue nummer als '#123456', #hotfix of #boyscout"
  exit 1
fi

# If the commit message is valid, exit with status 0
exit 0