#!/bin/bash


# Check if mvnd is installed, otherwise use mvn
if command -v mvnd &> /dev/null; then
    mvn_command="mvnd"
else
    mvn_command="mvn"
fi

echo using $mvn_command

$mvn_command spotless:check

if [ $? -ne 0 ]; then
    echo "Fout: Maven build gefaald, push afgebroken."
    exit 1
fi
